version: "3.9"
services:
  taskmanager:
    container_name: taskmanager
    build:
      context: .
      dockerfile: Dockerfile.local
    restart: always
    env_file: .env
    ports:
      - "${FRONTEND_PORT}:${FRONTEND_PORT}"
    volumes:
      - "./src:/usr/src/app/src"
    command: "npm run dev"